### PR TITLE
Add tox.ini, `python_requires` argument and additional trove classifiers.

### PR DESCRIPTION
**Pull request by shawnbrown**
I see that you're looking to set-up some online CI but I thought I'd push this in case you wanted a simple way to add more comprehensive testing locally.

This adds a `tox.ini` file that runs tests for Python versions 2.7 and 3.2 through 3.10, PyPy and PyPy3.
It also adds the associated trove classifiers as well as a `python_requires` argument to `setup()`.

### CODE REVIEW

**Comment by shawnbrown** [comment]
Here's the `tox` summary:

```
___________________________________ summary ____________________________________
  py27: commands succeeded
  py32: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
  py35: commands succeeded
  py36: commands succeeded
  py37: commands succeeded
  py38: commands succeeded
  py39: commands succeeded
  py310: commands succeeded
  pypy: commands succeeded
  pypy3: commands succeeded
  congratulations :)
```

Here's the full test run:
https://pastebin.com/EqZFXwHM

**Comment by olemb** [comment]
Thank you! It's nice to have some local tests as well.

Don't worry about the CI tests failing now. I'll fix that later.

**Comment by olemb** [comment]
Do you have all of these versions of Python installed locally? Here's it's only testing with py27 and py38.

```
tox -e py27,py38
```

I added `check-manifest` to the tests and wrote a bit about them in `CONTRIBUTING.md`.

**Comment by shawnbrown** [comment]
> Do you have all of these versions of Python installed locally?

I do. Although Python versions 3.5 and older are now all end-of-life, so you might want to change the tox list to:

    envlist = py27,py36,py37,py38,py39,py310,pypy,pypy3

But the versions of Python need to be installed on the system for tox to run them.

Even though 2.7 is end-of-life too, it's probably nice to keep it as long as the ecosystem supports it.

**Comment by olemb** [comment]
Yes. I also imagine dbfread is used in some environments where Python 2.7 is the only option, so it's best to support for a while still.

I think we can drop support for 3.2 officially and require 3.6.

**Comment by olemb** [comment]
In my system it just skips the Pythons I don't have installed.

**Comment by olemb** [comment]
Btw, do you think it's safe to assume dictionaries are ordered on 3.6? They happened to be in CPython but it's not official until 3.7.

**Comment by olemb** [comment]
I'm thinking of pypy for example.

**Comment by olemb** [comment]
Changed the list.

**Comment by shawnbrown** [comment]
> Btw, do you think it's safe to assume dictionaries are ordered on 3.6?

I wouldn't want to assume they were ordered in 3.6, but in the case of 3.6, you could could check for the platform to be sure:

    >>> import platform
    >>> platform.python_implementation()
    'CPython'

**Comment by shawnbrown** [comment]
I think the `python_requires` needs to be:

    python_requires='>=2.7.*, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*, !=3.5.*',

Reference: https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

**Comment by olemb** [comment]
Oh. I'll fix it. Why is 2.7 `'>=2.7.*'` though?

**Comment by olemb** [comment]
Here's what I ended up with:

```python
_py_version = (sys.version_info.major, sys.version_info.minor)
_py_impl = platform.python_implementation()
if _py_version > (3, 7) or (_py_version == (3, 6) and _py_impl == 'CPython'):
    ORDERED_DICT = dict
else:
    ORDERED_DICT = collections.OrderedDict
```

**Comment by olemb** [comment]
Oh, see a mistake. Should be `>= (3, 7)`.

**Comment by shawnbrown** [comment]
The `>=2.7.*` includes 3.6 and greater as well.

I was copying the format given in the [Packaging guide](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) which reads:

> If your package is for Python 2.6, 2.7, and all versions of Python 3 starting with 3.3, write:
>
>     python_requires='>=2.6, !=3.0.*, !=3.1.*, !=3.2.*, <4',

**Comment by olemb** [comment]
Updating the docs now.

**Comment by olemb** [comment]
Aha, the != means not equals. I somehow read it as exactly this version.

(Smack forehead.)

**Comment by olemb** [comment]
Updated.

**Pull request merged**
